# Generated by Django 3.2.5 on 2021-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
