# Generated by Django 3.2.5 on 2021-07-15 09:06

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='update')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
