# Generated by Django 3.2.5 on 2021-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_wnumber_contact_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='shedule',
            field=models.CharField(choices=[('9 to 10', '9 to 10'), ('10 to 11', '10 to 11')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
