# Generated by Django 3.2.5 on 2021-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210715_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.CharField(choices=[('09300950', '9:30 am - 9:50 am'), ('10001020', '10:00 am - 10:20 am'), ('10301050', '10:30 am - 10:50 am')], max_length=128),
        ),
    ]
